### ISSUE TITLE
"Electrodes" field not showing up in gui_session

### ISSUE THREAD

**Issue by KaiserArndt2** [petersenpeter/CellExplorer#24]
Hey Peter,

First off I want to say thank you for this awesome package!! It's helped loads!  

Going through the website, your tutorial on the session metadata video had a field for "electrodes" in the extracellular tab.  I am on windows and it doesn't show up for me, and I pulled the most recent updates to the code this morning.

![image](https://user-images.githubusercontent.com/46385650/108390340-93b93900-71de-11eb-9f1a-c3842f9ea3ac.png)

Not being able to specify electrode and measurements is giving me this error.  

![image](https://user-images.githubusercontent.com/46385650/108390459-b2b7cb00-71de-11eb-9f60-8147b83238f2.png)

Any help would be great, and thank you again!

Best,
Kaiser

**Comment by petersenpeter** [comment]
Hi Kaiser
The deep superficial calculation needs a probe layout, the error you received should have been a warning and I have pushed a fix for this to GitHub just now. 

The layout is a simple approximation for the vertical location and layout of the sites:
session.analysisTags.probesVerticalSpacing: in units of µm, e.g. 20
session.analysisTags.probesLayout: ['staggered','linear','poly2','poly3','poly5'] 

Check the first lines of the classification_DeepSuperficial script for further help. If you want to use the gui_session to add these, they are added in the analysis tags section (click the tab called tags). Otherwise, the script will use a default layout, but should not break this time.

See this tutorial on the deep superficial classification: 
https://cellexplorer.org/tutorials/deep-superficial-tutorial/

**Comment by KaiserArndt2** [comment]
Thank, and sorry for the late reply I was able to get this working.
